name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - name: Install big dependencies # see https://everest.github.io/nightly/general/02_detail_pre_setup.html#ubuntu
      shell: bash
      run: |
        sudo apt-get install libboost-all-dev libssl-dev libsqlite3-dev
    - name: Checkout `everest-cmake`
      shell: bash
      run: |
        cd ..
        git clone https://github.com/EVerest/everest-cmake
    - name: Install EDM (EVerest dependency manager) # see https://everest.github.io/nightly/general/03_quick_start_guide.html#everest-dependency-manager-edm
      shell: bash
      run: |
        cd ..
        git clone https://github.com/EVerest/everest-dev-environment
        cd everest-dev-environment/dependency_manager
        python3 -m pip install .
    - name: Run cmake
      shell: bash
      run: |
        cmake -B build/ \
          -D CMAKE_CXX_COMPILER=clang++-15 -D CXX_STANDARD=17 \
          -D CMAKE_EXPORT_COMPILE_COMMANDS=1 \
          -D CMAKE_BUILD_TYPE=Debug \
          -D CMAKE_GENERATOR="Unix Makefiles"

    - name: Run make
      shell: bash
      run: |
        cd build/
        make -j$(nproc) install
